### ISSUE TITLE
sync or cherry-pick from upstream

### ISSUE THREAD

**Issue by roytam1** [dbsoft/UXP#2]
since they pushed GRE with full history, it is possible to sync or cherry-pick.
https://repo.palemoon.org/MoonchildProductions/GRE

**Comment by dbsoft** [comment]
I am going to start making commits that match theirs, but there are so many questionable changes, like file reorganization for no clear reason... I don't think I can continue to cherry pick commits. The removals they have done for 30 are ridiculous.  I will be cherrypicking but probably not using git to do it directly... but will see once I get synched up to 30.1.

**Comment by roytam1** [comment]
and this is my selections:
https://github.com/roytam1/UXP/compare/a77f08a62fc559abe47754cf671e9bbf2248abc0...bf80b78247ea79d59779b4e4a8a89d5f45a69cfc

**Comment by dbsoft** [comment]
Thanks that is helpful, I have about half of those already sitting on my local machine headed for the 29.4.5 release. I'll probably commit the ones in yours that are applicable to 30 and then look at the master diff between 29.4.5 and 30.1 when 30.1 is eventually released.  I am just skipping 30.0.x completely.

**Comment by dbsoft** [comment]
We have merged with the Pale Moon UXP, so syncing and cherry picking is no longer required! :)
